version: "3"

services:
  helloworld:
    build:
      context: ./helloworld
      dockerfile: Dockerfile
    expose:
      - "3000"
    volumes:
      - ./notes:/mdlogdir
    environment:
      - NODE_ENV=production
      - DOMAIN=zapplebee.online
      - NOTES_DIR=/mdlogdir
    restart: always

  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /mnt/volume_sfo3_01/apps/.caddydata/data:/data
      - /mnt/volume_sfo3_01/apps/.caddydata/config:/config
    depends_on:
      - helloworld
